# Story Implementation Plan - Workflow Configuration
name: 'story-implementation-plan'
description: '스토리를 구현하기 전에 AI와 대화하며 완벽한 구현 계획서를 작성합니다. 코드베이스 검토, 기술적 질문/답변, 상세 계획 수립을 통해 AI가 100% 자동으로 개발할 수 있는 Implementation Plan을 생성합니다.'
author: 'Anyon'

# Paths
installed_path: '{project-root}/.anyon/custom/workflows/story-implementation-plan'
template: '{installed_path}/template.md'
instructions: '{installed_path}/instructions.md'
validation: '{installed_path}/checklist.md'

# Critical variables from config
config_source: '{project-root}/.anyon/anyon-builder/config.yaml'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

# User input - Story path provided as command argument
# Example: /story-implementation-plan anyon-docs/epics/epic-1-사용자-인증/story-1-회원가입.md
story_path: ""  # User provides this when invoking workflow

# Fixed paths - Planning documents location
docs_folder: '{project-root}/anyon-docs'
prd_path: '{docs_folder}/prd.md'
ux_design_path: '{docs_folder}/ux-design.md'
design_guide_path: '{docs_folder}/design-guide.md'
trd_path: '{docs_folder}/trd.md'
architecture_path: '{docs_folder}/architecture.md'
erd_path: '{docs_folder}/erd.md'

# Dynamic paths (extracted in instructions from story_path)
# epic_folder: dirname of story_path
# epic_path: {epic_folder}/epic.md
# output_plan_path: {epic_folder}/{story_name}-plan.md

# Output configuration
# Output file is dynamically generated in instructions.md based on story_path
# Pattern: {epic_folder}/{story_name}-plan.md
default_output_file: ''  # Set dynamically in instructions

# Invocation control
standalone: true  # Can be invoked directly by users

# Supporting files
conversation_guide: '{installed_path}/conversation-guide.md'
implementation_plan_template_file: '{installed_path}/implementation-plan-template.md'
