# Startup Launchpad Workflow Configuration
name: startup-launchpad
description: "Complete project kickstart workflow for non-technical founders. Generates comprehensive documentation suite (PRD, UX Design, Design Guide, TRD, Architecture, ERD) through conversational Q&A with real-time open-source discovery and curation."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
project_name: "{config_source}:project_name"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - Direct path to anyon-docs
output_folder: "{project-root}/anyon-docs"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-launchpad"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Templates for each document
prd_template: "{installed_path}/templates/prd-template.md"
ux_design_template: "{installed_path}/templates/ux-design-template.md"
design_guide_template: "{installed_path}/templates/design-guide-template.md"
trd_template: "{installed_path}/templates/trd-template.md"
architecture_template: "{installed_path}/templates/architecture-template.md"
erd_template: "{installed_path}/templates/erd-template.md"

# Output files - Direct to anyon-docs folder
prd_output: "{output_folder}/prd.md"
ux_design_output: "{output_folder}/ux-design.md"
design_guide_output: "{output_folder}/design-guide.md"
trd_output: "{output_folder}/trd.md"
architecture_output: "{output_folder}/architecture.md"
erd_output: "{output_folder}/erd.md"

# Tool Requirements
required_tools:
  - "WebSearch":
      description: "Real-time web search for open-source discovery and curation"
      critical: true
  - "WebFetch":
      description: "Fetch GitHub repository details and documentation"
      critical: true

standalone: true
