# Startup UX Design Workflow Configuration
name: startup-ux
description: "인터랙티브 HTML 목업(ui-ux.html) 생성. PRD의 서비스 유형, 플랫폼, 기능을 참조. 모든 버튼/클릭 요소가 연결된 클릭 가능한 프로토타입."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - planning subfolder in anyon-docs
output_folder: "{project-root}/anyon-docs/planning"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-ux"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Input: PRD document (YAML-based reference)
input_prd: "{output_folder}/prd.md"

# Output file
default_output_file: "{output_folder}/ui-ux.html"

# Skill Requirements - MUST be activated during workflow execution
required_skills:
  - skill: "frontend-design"
    trigger: "creating HTML wireframes"
    mandatory: true
    description: "와이어프레임 생성 시 반드시 사용 (그레이스케일, 이모지 금지 모드)"
  - skill: "document-consistency"
    trigger: "after document is saved to anyon-docs/planning/"
    mandatory: true
    description: "문서 저장 후 기존 문서들과 일관성 검사 수행"

standalone: true
