# Startup UX Design Workflow Configuration
name: startup-ux
description: "Create detailed UX Design document with obsessively specific user flows. References PRD for service type, platform, and features. This is the MOST CRITICAL workflow - spend time here for quality results. Auto-chains to startup-ui when complete."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - conversation subfolder in anyon-docs
output_folder: "{project-root}/anyon-docs/conversation"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-ux"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Input: PRD document (YAML-based reference)
input_prd: "{output_folder}/prd.md"

# Output file
default_output_file: "{output_folder}/ux-design.md"

# Next workflow in chain
next_workflow: "{project-root}/.anyon/anyon-method/workflows/startup-ui/workflow.yaml"

standalone: true
