# Startup TRD Workflow Configuration
name: startup-trd
description: "Create Technical Requirements Document with tech stack recommendations. Uses WebSearch/WebFetch to find 4-8 options for each technical decision. References PRD, UX Design, and UI Design Guide. Auto-chains to startup-architecture when complete."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - conversation subfolder in anyon-docs
output_folder: "{project-root}/anyon-docs/conversation"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-trd"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Inputs: Previous documents (YAML-based reference)
input_prd: "{output_folder}/prd.md"
input_ux: "{output_folder}/ux-design.md"
input_ui: "{output_folder}/ui-design-guide.md"

# Output file
default_output_file: "{output_folder}/trd.md"

# Next workflow in chain
next_workflow: "{project-root}/.anyon/anyon-method/workflows/startup-architecture/workflow.yaml"

# Tool Requirements
required_tools:
  - "WebSearch":
      description: "Search for technical solutions, frameworks, databases, and services"
      critical: true
  - "WebFetch":
      description: "Fetch technical details, benchmarks, and documentation"
      critical: true

standalone: true
