# Story Review Workflow Configuration
name: "story-review"
description: "스토리 구현 계획서를 기반으로 코드 리뷰를 수행하고, 비개발자용 수동 점검 체크리스트를 생성합니다. 인터랙티브 디버깅과 범위 관리를 지원합니다."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-builder/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.anyon/custom/workflows/story-review"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Input - Story implementation plan path (provided via prompt)
# Example: anyon-docs/epics/epic-1-사용자-인증/story-1-회원가입-plan.md
story_plan_path: "{{story_plan_path}}"

# Output configuration
# Review file saved alongside the plan file
# Example: anyon-docs/epics/epic-1-사용자-인증/story-1-회원가입-review.md
default_output_file: "{{review_output_path}}"

# Invocation control
standalone: true
