# Convert Legacy - ANYON v4 to v6 Converter Configuration
name: "convert-legacy"
description: "Converts legacy ANYON v4 or similar items (agents, workflows, modules) to Anyon Core compliant format with proper structure and conventions"
author: "Anyon"

# Critical variables load from config_source
config_source: "{project-root}/.anyon/anyon-builder/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-builder/workflows/convert-legacy"
template: false # This is an action/meta workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration - Creates converted items in appropriate module locations
default_output_folder: "{project-root}/.anyon/{{target_module}}/{{item_type}}/{{item_name}}"

# Sub-workflows that may be invoked for conversion
sub_workflows:
  - create_agent: "{project-root}/.anyon/anyon-builder/workflows/create-agent/workflow.yaml"
  - create_workflow: "{project-root}/.anyon/anyon-builder/workflows/create-workflow/workflow.yaml"
  - create_module: "{project-root}/.anyon/anyon-builder/workflows/create-module/workflow.yaml"

standalone: true
