# AI Code Technical Debt Resolution Workflow
name: "resolve-ai-tech-debt"
description: "AI로 생성된 코드의 기술부채를 종합적으로 분석하고 해결하는 워크플로우. 죽은 코드 제거, 코드 품질 개선, 테스트 커버리지 확보, 아키텍처 검토, 레거시 코드 정리를 수행합니다."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/resolve-ai-tech-debt"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/tech-debt-report-{{date}}.md"
remediation_log_file: "{output_folder}/tech-debt-remediation-log-{{date}}.md"

# Analysis scope configuration (user can specify)
target_directory: "{project-root}"
excluded_patterns:
  - "node_modules/**"
  - "vendor/**"
  - ".git/**"
  - "dist/**"
  - "build/**"
  - "__pycache__/**"
  - "*.min.js"
  - "*.min.css"

# Debt categories to analyze
debt_categories:
  dead_code:
    enabled: true
    priority: "high"
    description: "미사용 함수, 변수, import, 클래스 탐지"
  code_quality:
    enabled: true
    priority: "high"
    description: "복잡도, 중복, 코드 스멜, 명명규칙 검토"
  test_coverage:
    enabled: true
    priority: "medium"
    description: "테스트 커버리지 분석 및 누락 영역 식별"
  architecture:
    enabled: true
    priority: "medium"
    description: "결합도/응집도, 패턴 일관성, 의존성 분석"
  legacy_code:
    enabled: true
    priority: "low"
    description: "구버전 API, deprecated 패턴, 업그레이드 필요 영역"
  database:
    enabled: true
    priority: "high"
    description: "스키마, 쿼리, 마이그레이션, ORM/모델, 데이터 무결성 분석"
    subcategories:
      schema:
        description: "미사용 테이블/컬럼, 인덱스 최적화, 정규화, FK 제약조건"
      query:
        description: "N+1 쿼리, 비효율적 쿼리, Raw SQL/ORM 혼용"
      migration:
        description: "미적용 마이그레이션, 스키마 불일치, 롤백 가능성"
      orm_model:
        description: "미사용 모델, 관계 정의, 유효성 검증, Loading 문제"
      data_integrity:
        description: "고아 레코드, 중복 데이터, NULL 처리 일관성"

# Recommended tools (optional - enhance analysis if available)
recommended_tools:
  - name: "ESLint/Pylint/etc"
    description: "언어별 린터로 코드 품질 분석"
  - name: "SonarQube"
    description: "종합적인 코드 품질 및 보안 분석"
  - name: "CodeScene"
    description: "코드 건강도 측정 및 기술부채 정량화"

# Invocation control
standalone: true

# Web bundle configuration
web_bundle:
  name: "resolve-ai-tech-debt"
  description: "AI로 생성된 코드의 기술부채를 종합적으로 분석하고 해결하는 워크플로우"
  author: "Anyon"

  instructions: ".anyon/anyon-method/workflows/resolve-ai-tech-debt/instructions.md"
  validation: ".anyon/anyon-method/workflows/resolve-ai-tech-debt/checklist.md"
  template: ".anyon/anyon-method/workflows/resolve-ai-tech-debt/template.md"

  web_bundle_files:
    - ".anyon/anyon-method/workflows/resolve-ai-tech-debt/workflow.yaml"
    - ".anyon/anyon-method/workflows/resolve-ai-tech-debt/instructions.md"
    - ".anyon/anyon-method/workflows/resolve-ai-tech-debt/checklist.md"
    - ".anyon/anyon-method/workflows/resolve-ai-tech-debt/template.md"
