# PM Opensource - Open Source Repository Clone Workflow
name: "pm-opensource"
description: "PRD 문서에서 오픈소스 레포지토리 정보를 찾아 현재 작업 디렉토리에 clone한 후, PRD에 clone 경로를 업데이트합니다. PM Orchestrator 실행 전에 수행합니다."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
output_folder: "{project-root}/anyon-docs/planning"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/pm-opensource"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Input/Output document - PRD 파일 사용
prd_doc: "{output_folder}/prd.md"

# Clone location - 현재 작업 디렉토리 (Claude Code 실행 위치)
clone_base_path: "{project-root}"

# Invocation control
standalone: true
