# Brainstorming Session Workflow Configuration
name: "brainstorming"
description: "Facilitate interactive brainstorming sessions using diverse creative techniques. This workflow facilitates interactive brainstorming sessions using diverse creative techniques. The session is highly interactive, with the AI acting as a facilitator to guide the user through various ideation methods to generate and refine creative solutions."
author: "Anyon"

# Critical variables load from config_source
config_source: "{project-root}/.anyon/cis/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
date: system-generated

# Context can be provided via data attribute when invoking
# Example: data="{path}/context.md" provides domain-specific guidance

# Module path and component files
installed_path: "{project-root}/.anyon/core/workflows/brainstorming"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
brain_techniques: "{installed_path}/brain-methods.csv"

# Output configuration
default_output_file: "{output_folder}/brainstorming-session-results-{{date}}.md"

standalone: true

web_bundle:
  name: "brainstorming"
  description: "Facilitate interactive brainstorming sessions using diverse creative techniques. This workflow facilitates interactive brainstorming sessions using diverse creative techniques. The session is highly interactive, with the AI acting as a facilitator to guide the user through various ideation methods to generate and refine creative solutions."
  author: "Anyon"
  template: ".anyon/core/workflows/brainstorming/template.md"
  instructions: ".anyon/core/workflows/brainstorming/instructions.md"
  brain_techniques: ".anyon/core/workflows/brainstorming/brain-methods.csv"
  use_advanced_elicitation: true
  web_bundle_files:
    - ".anyon/core/workflows/brainstorming/instructions.md"
    - ".anyon/core/workflows/brainstorming/brain-methods.csv"
    - ".anyon/core/workflows/brainstorming/template.md"
