# Startup Design Guide Workflow Configuration
name: startup-design-guide
description: "디자인 가이드 정의 - 색상, 폰트, 스타일만. 기술 스택(React, MUI 등)은 TRD에서 처리."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder
output_folder: "{project-root}/anyon-docs/planning"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-ui"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Inputs
input_prd: "{output_folder}/prd.md"
input_ux: "{output_folder}/ui-ux.html"

# Output file - renamed from ui-lib.md to design-guide.md
default_output_file: "{output_folder}/design-guide.md"

standalone: true
