# Startup UI Design Guide Workflow Configuration
name: startup-ui
description: "Create UI Design Guide with open-source component library recommendations. Uses WebSearch/WebFetch to find 4-8 options for each decision. References PRD and UX Design. Auto-chains to startup-trd when complete."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - conversation subfolder in anyon-docs
output_folder: "{project-root}/anyon-docs/conversation"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-ui"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Inputs: PRD and UX Design documents (YAML-based reference)
input_prd: "{output_folder}/prd.md"
input_ux: "{output_folder}/ux-design.md"

# Output file
default_output_file: "{output_folder}/ui-design-guide.md"

# Next workflow in chain
next_workflow: "{project-root}/.anyon/anyon-method/workflows/startup-trd/workflow.yaml"

# Tool Requirements
required_tools:
  - "WebSearch":
      description: "Search for UI component libraries and design resources"
      critical: true
  - "WebFetch":
      description: "Fetch details from GitHub, npm, and documentation sites"
      critical: true

standalone: true
