# Edit Module - Module Editor Configuration
name: "edit-module"
description: "Edit existing ANYON modules (structure, agents, workflows, documentation) while following all best practices"
author: "Anyon"

# Critical variables load from config_source
config_source: "{project-root}/.anyon/anyon-builder/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Required Data Files - Critical for understanding module conventions
module_structure_guide: "{project-root}/.anyon/anyon-builder/workflows/create-module/module-structure.md"

# Related workflow editors
agent_editor: "{project-root}/.anyon/anyon-builder/workflows/edit-agent/workflow.yaml"
workflow_editor: "{project-root}/.anyon/anyon-builder/workflows/edit-workflow/workflow.yaml"

# Reference examples - for learning patterns
anyon_method_module_dir: "{project-root}/.anyon/anyon-method/"
anyon_builder_module_dir: "{project-root}/.anyon/anyon-builder/"
cis_module_dir: "{project-root}/.anyon/cis/"
existing_agents_dir: "{project-root}/.anyon/*/agents/"
existing_workflows_dir: "{project-root}/.anyon/*/workflows/"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-builder/workflows/edit-module"
template: false # This is an action workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true

# Web bundle configuration