# Startup PRD Workflow Configuration
name: startup-prd
description: "Create Product Requirements Document for startups. Defines service type, platform, target users, core features, and business model. Auto-chains to startup-ux when complete."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder - conversation subfolder in anyon-docs
output_folder: "{project-root}/anyon-docs/conversation"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-prd"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output file
default_output_file: "{output_folder}/prd.md"

# Next workflow in chain
next_workflow: "{project-root}/.anyon/anyon-method/workflows/startup-ux/workflow.yaml"

standalone: true
