# Startup Epics & Stories Generator - Workflow Configuration
name: startup-epics-stories
description: "스타트업 런치패드 워크플로우에서 생성된 6개 문서(PRD, UX Design, Design Guide, TRD, Architecture, ERD)를 분석하여 전체 프로젝트의 에픽과 스토리를 자동 생성합니다."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Smart input file references - 스타트업 런치패드 6개 문서
input_file_patterns:
  prd:
    description: "Product Requirements Document"
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"
    load_strategy: "INDEX_GUIDED"
  ux_design:
    description: "UX Design Specification"
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
    load_strategy: "FULL_LOAD"
  design_guide:
    description: "Design Guide with UI components"
    whole: "{output_folder}/*design*guide*.md"
    sharded: "{output_folder}/*design*guide*/index.md"
    load_strategy: "FULL_LOAD"
  trd:
    description: "Technical Requirements Document"
    whole: "{output_folder}/*trd*.md"
    sharded: "{output_folder}/*trd*/index.md"
    load_strategy: "INDEX_GUIDED"
  architecture:
    description: "Architecture Document"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/index.md"
    load_strategy: "FULL_LOAD"
  erd:
    description: "Entity Relationship Diagram"
    whole: "{output_folder}/*erd*.md"
    sharded: "{output_folder}/*erd*/index.md"
    load_strategy: "FULL_LOAD"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-epics-stories"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/template.md"
validation: "{installed_path}/checklist.md"

# Output configuration - 에픽별 서브폴더 구조
default_output_file: "{output_folder}/epics.md"
epics_folder: "{output_folder}/epics"

standalone: true
