# Startup Architecture Workflow Configuration
name: startup-architecture
description: "시스템 아키텍처. 구조, 데이터 흐름, 확장성, 보안. 기술스택/API는 제외."
author: "Anyon"

# Critical variables from config
config_source: "{project-root}/.anyon/anyon-method/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Output folder
output_folder: "{project-root}/anyon-docs/planning"

# Module path and component files
installed_path: "{project-root}/.anyon/anyon-method/workflows/startup-architecture"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Inputs
input_prd: "{output_folder}/prd.md"
input_ux: "{output_folder}/ui-ux.html"
input_trd: "{output_folder}/trd.md"

# Output file
default_output_file: "{output_folder}/architecture.md"

standalone: true
